name: blockify_medical
description: Blockify - medical blockchain

version: 1.0.0+3

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  flutter_country_picker: ^0.1.6
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.2.0
  google_maps_flutter: ^0.5.22+2
  permission_handler: ^4.2.0+hotfix.3
  dio: ^3.0.8
  shared_preferences: ^0.5.6+1  
  provider: ^4.0.4
  progress_dialog: ^1.2.1
  
flutter_icons:
  android: true
  image_path: "assets/icons/blockify.png"

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
   - assets/images/